/*
  MENÜ SCHNELL BEARBEITEN
  Die Angaben entsprechen den drei PDF-Karten vom 26.09.2026.
*/
const imagePool = Array.from({ length: 24 }, (_, i) => `assets/images/dish-${String(i + 1).padStart(2, "0")}.webp`);
const logoImage = "assets/images/logo.png";

const menuItem = (id, code, category, name, description, price, allergens = "", tags = [], image = logoImage) => ({
  id, code, category, name, description, price, allergens, tags, image
});
const L = menuItem;
const D = menuItem;

const lunchSupplementMenu = [
  L("L1", "1", "Suppen & Snacks", "Pekingsuppe", "Entenfleisch, Gemüse und Ei, sauer-scharf", 3.9, "5, 7, C"),
  L("L2", "2", "Suppen & Snacks", "Thai-Suppe", "Hühnerfleisch und Gemüse", 4.9, "5, 7, B", ["scharf"]),
  L("L3", "3", "Suppen & Snacks", "Gyoza-Chicken", "Teigtasche mit Hühnerfleisch und Teriyaki-Sauce", 5.9, "7"),
  L("L4", "4", "Suppen & Snacks", "Sommerrolle", "4 Reispapierrollen mit Garnelen, frischem Salat, Kräutern und Hoisin-Sauce", 8.5, "7, B", [], imagePool[19]),
  L("L5", "5", "Suppen & Snacks", "Nem", "2 vietnamesische Frühlingsrollen mit Garnelen, Schweinefleisch, Rindfleisch, Glasnudeln und Gemüse, serviert mit Fischsauce", 5.5, "5, 7, C, D, F", ["beliebt"]),
  L("L6", "6", "Suppen & Snacks", "Gebratener Reis mit Hühnerfleisch", "Mit Gemüse, Sojasprossen und Ei", 8.9, "5, 7, C, F, K", ["beliebt"]),
  L("L7", "7", "Suppen & Snacks", "Gebratener Reis mit knuspriger Ente", "Mit Gemüse, Sojasprossen und Ei", 14.5, "5, 7, C, F, K", ["beliebt"]),
  L("L8", "8", "Suppen & Snacks", "Gebratener Reis mit Riesengarnelen", "Mit Gemüse, Sojasprossen und Ei", 14.9, "5, 7, B, C, F, K"),
  L("L9", "9", "Suppen & Snacks", "Gebratene Nudeln mit Hühnerfleisch", "Mit Gemüse, Sojasprossen und Ei", 8.9, "5, 7, C, F", ["beliebt"]),
  L("L10", "10", "Suppen & Snacks", "Gebratene Nudeln mit paniertem Hühnerfleisch", "Mit Gemüse, Sojasprossen und Ei", 12.9, "5, 7, C, F"),
  L("L11", "11", "Suppen & Snacks", "Gebratene Nudeln mit geröstetem Chicken", "Mit Gemüse, Sojasprossen und Ei", 13.5, "5, 7, C, F"),
  L("L12", "12", "Suppen & Snacks", "Gebratene Nudeln mit knuspriger Ente", "Mit Gemüse, Sojasprossen und Ei", 14.5, "5, 7, C, F", ["beliebt"]),
  L("L13", "13", "Suppen & Snacks", "Gebratene Nudeln mit Riesengarnelen", "Mit Gemüse, Sojasprossen und Ei", 14.9, "5, 7, B, C, F"),
  L("L15", "15", "Suppen & Snacks", "Pho mit Rindfleisch", "Reisbandnudelsuppe mit frischen Kräutern", 13.9),
  L("L16", "16", "Suppen & Snacks", "Pho mit Hühnerfleisch", "Reisbandnudelsuppe mit frischen Kräutern", 13.5),

  L("L20", "20", "Chop Suey", "Chop Suey Sauce mit Hühnerfleisch", "Frisches Gemüse und Reis", 12.9, "5, 7, B, K, F"),
  L("L21", "21", "Chop Suey", "Chop Suey Sauce mit paniertem Hühnerfleisch", "Frisches Gemüse und Reis", 13.5, "5, 7, B, K, F"),
  L("L22", "22", "Chop Suey", "Chop Suey Sauce mit geröstetem Chicken", "Frisches Gemüse und Reis", 13.9, "5, 7, B, K, F"),
  L("L23", "23", "Chop Suey", "Chop Suey Sauce mit knuspriger Ente", "Frisches Gemüse und Reis", 14.9, "5, 7, B, K, F", ["beliebt"]),
  L("L24", "24", "Chop Suey", "Chop Suey Sauce mit Rindfleisch", "Frisches Gemüse und Reis", 13.9, "5, 7, B, K, F"),
  L("L25", "25", "Chop Suey", "Chop Suey Sauce mit Riesengarnelen", "Frisches Gemüse und Reis", 14.9, "5, 7, B, K, F"),
  L("L30", "30", "Süß-Sauer", "Süß-Sauer Sauce mit Hühnerfleisch", "Frisches Gemüse und Reis", 12.5, "5, 7, K"),
  L("L31", "31", "Süß-Sauer", "Süß-Sauer Sauce mit paniertem Hühnerfleisch", "Frisches Gemüse und Reis", 13.3, "5, 7, K"),
  L("L32", "32", "Süß-Sauer", "Süß-Sauer Sauce mit knuspriger Ente", "Frisches Gemüse und Reis", 14.5, "5, 7, K", ["beliebt"]),
  L("L40", "40", "Erdnuss", "Erdnuss-Sauce mit Hühnerfleisch", "Frisches Gemüse und Reis", 12.9, "5, 7, E, G, K"),
  L("L41", "41", "Erdnuss", "Erdnuss-Sauce mit paniertem Hühnerfleisch", "Frisches Gemüse und Reis", 13.5, "5, 7, E, G, K"),
  L("L42", "42", "Erdnuss", "Erdnuss-Sauce mit geröstetem Chicken", "Frisches Gemüse und Reis", 14.3, "5, 7, E, G, K"),
  L("L43", "43", "Erdnuss", "Erdnuss-Sauce mit knuspriger Ente", "Frisches Gemüse und Reis", 14.9, "5, 7, E, G, K", ["beliebt"]),
  L("L50", "50", "Red Curry", "Red Curry mit Hühnerfleisch", "Frisches Gemüse und Reis", 12.9, "5, 7, G, K", ["scharf"]),
  L("L51", "51", "Red Curry", "Red Curry mit paniertem Hühnerfleisch", "Frisches Gemüse und Reis", 13.9, "5, 7, G, K", ["scharf"]),
  L("L52", "52", "Red Curry", "Red Curry mit geröstetem Chicken", "Frisches Gemüse und Reis", 14.3, "5, 7, G, K", ["scharf"]),
  L("L53", "53", "Red Curry", "Red Curry mit knuspriger Ente", "Frisches Gemüse und Reis", 14.9, "5, 7, G, K", ["scharf", "beliebt"]),
  L("L54", "54", "Red Curry", "Red Curry mit Rindfleisch", "Frisches Gemüse und Reis", 13.9, "5, 7, G, K", ["scharf"]),
  L("L55", "55", "Red Curry", "Red Curry mit Riesengarnelen", "Frisches Gemüse und Reis", 14.9, "5, 7, B, G, K", ["scharf"]),
  L("L60", "60", "Mango", "Mango-Sauce mit Hühnerfleisch", "Frisches Gemüse und Reis", 12.9, "5, 7, K, F"),
  L("L61", "61", "Mango", "Mango-Sauce mit paniertem Hühnerfleisch", "Frisches Gemüse und Reis", 13.5, "5, 7, K, F"),
  L("L63", "63", "Mango", "Mango-Sauce mit knuspriger Ente", "Frisches Gemüse und Reis", 14.9, "5, 7, K, F", ["beliebt"]),
  L("L64", "64", "Mango", "Mango-Sauce mit Riesengarnelen", "Frisches Gemüse und Reis", 14.9, "5, 7, B, K, F"),
  L("L65", "65", "BBQ", "BBQ Sauce mit Hühnerfleisch", "Frisches Gemüse und Reis", 12.9, "5, 7, B, E, F"),
  L("L66", "66", "BBQ", "BBQ Sauce mit paniertem Hühnerfleisch", "Frisches Gemüse und Reis", 13.5, "5, 7, B, E, F"),
  L("L67", "67", "BBQ", "BBQ Sauce mit geröstetem Chicken", "Frisches Gemüse und Reis", 13.9, "5, 7, B, E, F"),
  L("L68", "68", "BBQ", "BBQ Sauce mit knuspriger Ente", "Frisches Gemüse und Reis", 14.9, "5, 7, B, E, F", ["beliebt"]),
  L("L69", "69", "BBQ", "BBQ Sauce mit Rindfleisch", "Frisches Gemüse und Reis", 13.9, "5, 7, B, E, F"),
  L("L71", "71", "Reisnudeln & Spezial", "Bun Nem", "Vietnamesische Frühlingsrollen mit Garnelen, Schweinefleisch, Rindfleisch, Reisnudeln und Gemüse", 10.0, "5, 7, E, F", ["beliebt"]),
  L("L72", "72", "Reisnudeln & Spezial", "Bun Bo Nam Bo", "Rindfleisch mit Reisnudeln, Zwiebeln, Sojasprossen und Zitronengras", 10.0, "5, 7, E, F", ["beliebt"]),
  L("L75", "75", "Reisnudeln & Spezial", "Pad Thai", "Gebratene Reisbandnudeln mit Garnelen, Pak Choi und Pad Thai Art Sauce", 14.9, "5, 7, B, E, F", ["scharf"]),
  L("L78", "78", "Reisnudeln & Spezial", "Gebratene Udon-Nudeln", "Mit paniertem Hühnerfleisch, Pak Choi und Teriyaki-Sauce", 13.9, "5, 7, E, F"),
  L("L79", "79", "Reisnudeln & Spezial", "Tom Yum Thai Art", "Udon-Nudelsuppe mit Riesengarnelen, Pak Choi, Karotten und Paprika", 14.9, "5, 7, B", ["scharf"]),
  L("L80", "80", "Vegetarisch", "Chop Suey Sauce mit frischem Gemüse", "Mit Reis", 11.9, "5, 7, F, K", ["vegetarisch", "vegan"]),
  L("L81", "81", "Vegetarisch", "Erdnuss-Sauce mit frischem Gemüse", "Mit Reis", 11.9, "5, 7, E, G, K", ["vegetarisch"]),
  L("L82", "82", "Vegetarisch", "Red Curry mit frischem Gemüse", "Mit Reis", 11.9, "5, 7, G, K", ["vegetarisch", "scharf"]),
  L("L83", "83", "Vegetarisch", "Mango-Sauce mit frischem Gemüse", "Mit Reis", 11.9, "7, G, K", ["vegetarisch"]),
  L("L84", "84", "Vegetarisch", "BBQ Sauce mit frischem Gemüse", "Mit Reis", 11.9, "7, G, K", ["vegetarisch", "scharf"]),
  L("L85", "85", "Vegetarisch", "Chop Suey Sauce mit Tofu und frischem Gemüse", "Mit Reis", 12.9, "5, 7, F, K", ["vegetarisch", "vegan"]),
  L("L86", "86", "Vegetarisch", "Erdnuss-Sauce mit Tofu und frischem Gemüse", "Mit Reis", 12.9, "5, 7, E, G, F, K", ["vegetarisch"]),
  L("L87", "87", "Vegetarisch", "Red Curry mit Tofu und frischem Gemüse", "Mit Reis", 12.9, "5, 7, G, F, K", ["vegetarisch", "scharf"]),
  L("L88", "88", "Vegetarisch", "Mango-Sauce mit Tofu und frischem Gemüse", "Mit Reis", 12.9, "7, G, F, K", ["vegetarisch"]),
  L("L89", "89", "Vegetarisch", "BBQ Sauce mit Tofu und frischem Gemüse", "Mit Reis", 12.9, "5, 7, F, K", ["vegetarisch", "scharf"]),
  L("L90", "90", "Vegetarisch", "Minifrühlingsrollen", "10 Stück, vegetarisch", 4.5, "5, A, F", ["vegetarisch", "vegan"]),
  L("L91", "91", "Vegetarisch", "Vegan Gyoza", "Teigtasche mit Gemüse und Teriyaki-Sauce", 6.0, "5, A, F", ["vegetarisch", "vegan"]),
  L("L92", "92", "Vegetarisch", "Sommerrolle", "Reispapier mit Bio-Tofu, Salat, frischen Kräutern und Hoisin-Sauce", 7.5, "7, D", ["vegetarisch"], imagePool[21]),
  L("L93", "93", "Vegetarisch", "Bratreis mit Gemüse und Ei", "Vegetarisch", 7.9, "5, 7, C, F", ["vegetarisch"]),
  L("L94", "94", "Vegetarisch", "Bratnudeln mit Gemüse und Ei", "Vegetarisch", 7.9, "5, 7, C, F", ["vegetarisch"]),
  L("L95", "95", "Vegetarisch", "Pad Thai mit Bio-Tofu", "Gebratene Reisbandnudeln mit Bio-Tofu, Pak Choi und Pad Thai Art Sauce", 13.5, "5, 7, E, F", ["vegetarisch"]),
  L("L96", "96", "Vegetarisch", "Pho Tofu", "Reisbandnudelsuppe mit Bio-Tofu und frischen Kräutern", 13.0, "5, 7, D, F", ["vegetarisch"]),
  L("L97", "97", "Vegetarisch", "Tom Yum Thai Art mit Bio-Tofu", "Udon-Nudelsuppe mit Bio-Tofu, Pak Choi, Karotten und Paprika", 13.0, "5, 7, F", ["vegetarisch", "scharf"]),
  L("L98", "98", "Vegetarisch", "Bun-Reisnudeln mit Tofu", "Reisnudeln mit Tofu, Salat, frischen Kräutern, Erdnüssen und Fischsauce", 12.5, "5, 7, D, E", ["vegetarisch"]),
  ...[
    ["LD1", "D1", "Cola / Zero / Mezzo", "0,4 l", 3.0], ["LD2", "D2", "Fanta", "0,4 l", 3.0],
    ["LD3", "D3", "Sprite", "0,4 l", 3.0], ["LD4", "D4", "Ginger Ale", "0,4 l", 3.0],
    ["LD5", "D5", "Still / Sprudel", "0,4 l", 3.0], ["LD6", "D6", "Apfel", "Saft oder Schorle, 0,4 l", 3.0],
    ["LD7", "D7", "Maracuja", "Saft oder Schorle, 0,4 l", 3.0], ["LD8", "D8", "Johannisbeere", "Saft oder Schorle, 0,4 l", 3.0],
    ["LD9", "D9", "Lychee", "Saft oder Schorle, 0,4 l", 3.0], ["LD10", "D10", "Ganter Bier", "0,5 l", 4.9],
    ["LD11", "D11", "Ganter Bier ohne Alkohol", "0,5 l", 4.9], ["LD12", "D12", "Hefeweizen", "0,5 l", 4.9],
    ["LD13", "D13", "Asian Bier Kirin", "0,3 l", 4.9], ["LD14", "D14", "Weißwein", "0,2 l", 4.5],
    ["LD15", "D15", "Rotwein", "0,2 l", 4.5], ["LD16", "D16", "Jasmintee", "Tee", 4.5],
    ["LD17", "D17", "Kamillentee", "Tee", 4.5], ["LD18", "D18", "Ingwertee", "Tee", 4.5],
    ["LD19", "D19", "Minzetee", "Tee", 4.5]
  ].map(([id, code, name, description, price]) => L(id, code, "Getränke", name, description, price))
];

const lunchClassicMenu = [
  ...[
    ["B1", "Bratnudeln mit Gemüse und Ei", [5.0, 6.0, 7.9], "5, 7, C", ["vegetarisch"]],
    ["B2", "Bratnudeln mit Hühnerfleisch und Ei", [5.5, 6.5, 8.9], "5, 7, C", ["beliebt"]],
    ["B3", "Bratreis mit Gemüse und Ei", [5.0, 6.0, 7.9], "5, 7, C", ["vegetarisch"]],
    ["B4", "Bratreis mit Hühnerfleisch und Ei", [5.5, 6.5, 8.9], "5, 7, C", ["beliebt"]],
    ["B5", "Bratnudeln mit knusprigem Hähnchenstück", [5.5, 6.5, 8.9], "5, A1, C, K", ["beliebt"]]
  ].flatMap(([code, name, prices, allergens, tags]) => ["Klein", "Groß", "Mega"].map((size, index) => L(`${code}-${size[0]}`, code, "Box to go", name, size, prices[index], allergens, tags))),
  L("B6", "B6", "Box to go", "Bratnudeln mit knuspriger Ente", "Groß", 14.5, "5, 7, C", ["beliebt"]),
  L("B7", "B7", "Box to go", "Bratnudeln mit geröstetem Chicken", "Groß", 13.5, "5, 7, C", ["beliebt"]),
  L("B8", "B8", "Box to go", "Bratnudeln mit Minifrühlingsrolle", "Groß", 6.5, "5, 7, C, A1", ["vegetarisch", "beliebt"]),
  L("B9", "B9", "Box to go", "Chickenstreifen mit Reis, süß-sauer", "Groß", 6.5, "5, 7, A1", ["beliebt"]),
  L("B10", "B10", "Box to go", "Gemüse Chop Suey mit Reis", "Einheitsgröße", 7.9, "5, 7, F", ["vegetarisch", "vegan"]),
  L("B11", "B11", "Box to go", "Gemüse Chop Suey mit Hühnerfleisch und Reis", "Einheitsgröße", 7.9, "5, 7, F"),
  L("B12", "B12", "Box to go", "Erdnuss-Sauce mit Gemüse und Reis", "Einheitsgröße", 7.9, "5, 7, E, G", ["vegetarisch"]),
  L("B13", "B13", "Box to go", "Erdnuss-Sauce mit Hühnerfleisch, Gemüse und Reis", "Einheitsgröße", 7.9, "5, 7, E, G"),
  L("B14", "B14", "Box to go", "Red Curry mit Gemüse und Reis", "Einheitsgröße", 7.9, "5, 7, G", ["vegetarisch", "scharf"]),
  L("B15", "B15", "Box to go", "Red Curry mit Hühnerfleisch, Gemüse und Reis", "Einheitsgröße", 7.9, "5, 7, G", ["scharf"]),
  L("B16", "B16", "Box to go", "Mango mit Gemüse und Reis", "Einheitsgröße", 7.9, "5, 7, G", ["vegetarisch"]),
  L("B17", "B17", "Box to go", "Mango mit Hühnerfleisch, Gemüse und Reis", "Einheitsgröße", 7.9, "5, 7, G"),
  L("B20", "B20", "Box to go", "Minifrühlingsrollen", "10 Stück, vegetarisch", 4.5, "5, 7, A1", ["vegetarisch", "vegan"]),
  L("B21", "B21", "Box to go", "Sommerrolle mit Mango", "Mit Hoisin-Sauce", 7.5, "5, 7, D, F", ["vegetarisch"]),
  L("B22", "B22", "Box to go", "Sommerrolle mit Garnelen", "Mit Hoisin-Sauce", 8.5, "5, 7, B, D")
];

const lunchMenu = [...lunchClassicMenu, ...lunchSupplementMenu];

const dinnerMenu = [
  D("1", "1", "Vorspeisen", "Pekingsuppe", "Entenfleisch mit Gemüse und Ei, sauer-scharf", 5.0, "5, 7, C", ["beliebt"]),
  D("2", "2", "Vorspeisen", "Thaisuppe", "Garnelen, Hähnchen, Gemüse und Kokosmilch", 5.9, "5, 7, B", ["scharf"]),
  D("3", "3", "Vorspeisen", "Sake Miso", "Misosuppe mit Lachs, Seetang und Pilzen", 6.5, "7, D"),
  D("4", "4", "Vorspeisen", "Nem", "Vietnamesische Frühlingsrollen mit Garnelen, Schweinefleisch, Rindfleisch, Glasnudeln und Gemüse, serviert mit Fischsauce", 6.5, "5, 7, C, D, F", ["beliebt"]),
  D("5", "5", "Vorspeisen", "Minifrühlingsrolle", "Mini-Frühlingsrollen mit Gemüsefüllung", 5.0, "5, 7, A1", ["vegetarisch"]),
  D("6", "6", "Vorspeisen", "Chicken Karaage", "Chicken mit Trüffel-Mayonnaise", 6.0, "7", ["beliebt"]),
  D("7", "7", "Vorspeisen", "Gyoza vegetarisch", "Gebratene japanische Teigtaschen mit Ponzu-Sauce", 6.9, "5, 7, F, K", ["vegetarisch"], imagePool[16]),
  D("8", "8", "Vorspeisen", "Gyoza Hühnerfleisch", "Gebratene japanische Teigtaschen mit Ponzu-Sauce", 6.9, "5, 7, F, K", [], imagePool[16]),
  D("9", "9", "Vorspeisen", "Edamame", "Gedämpfte Sojabohnen mit Meersalz", 5.0, "F", ["vegetarisch", "vegan"]),
  D("10", "10", "Vorspeisen", "Kimchi", "Eingelegter Chinakohl nach koreanischer Art", 4.5, "7", ["vegetarisch", "scharf"]),
  D("11", "11", "Vorspeisen", "Tempura Ebi", "Knusprige Riesengarnelen im Tempurateig, serviert mit Mayonnaise", 6.0, "A1, B, C, G", ["beliebt"], imagePool[6]),
  D("12", "12", "Vorspeisen", "Seetang", "Japanischer Wakame-Seetangsalat mit Sesam", 5.0, "K", ["vegetarisch", "vegan"]),
  D("13", "13", "Vorspeisen", "Sommerrolle Mango", "2 Stück mit Salat, eingelegten Möhren, Gurke, Kohlrabi, Rettich, Kräutern, Erdnüssen und Hoisin-Dip", 5.5, "7, E", ["vegetarisch"]),
  D("14", "14", "Vorspeisen", "Sommerrolle Garnelen", "2 Stück mit Salat, eingelegten Möhren, Gurke, Kohlrabi, Rettich, Kräutern, Erdnüssen und Hoisin-Dip", 6.0, "7, B, E", [], imagePool[19]),
  D("15", "15", "Vorspeisen", "Maiwok Tapas Mix", "Für 2 Personen: Sommerrollen mit Garnelen, Gyoza vegetarisch, Kimchi und Nem Vietnam", 19.0, "5, 7, B, C, D, E", ["beliebt"], imagePool[18]),
  D("16", "16", "Salate", "Garnelen-Mango", "Salat mit Mango, Garnelen, Kräutern, Zwiebeln, Edamame, Erdnüssen und Limetten-Chili-Dressing", 13.9, "5, 7, B, E", ["scharf"], imagePool[20]),
  D("17", "17", "Salate", "Avocado-Tempura Chicken", "Grüner Salat mit Avocado, Tempura Chicken, Edamame, Chili, Koriander, Erdnüssen und Sesamsoße", 11.9, "5, 7, C, E", ["beliebt"], imagePool[8]),
  D("20", "20", "Bowls", "Bowl Lachs - roher Lachs", "Sushireis, roher Lachs, Seetang, Rucola, Kimchi, Avocado, Edamame, Lachskaviar, Erdnüsse, Sesam und Unagisauce", 15.9, "7, D", ["beliebt"]),
  D("21", "21", "Bowls", "Bowl Udon", "Grüner Salat mit Udon, Avocado, Edamame, Teriyaki Chicken, Koriander, Chili, Erdnüssen und Sesamsoße", 14.5, "5, 7, C, K", [], imagePool[8]),
  D("25", "25", "Hauptspeisen", "Bun Tofu", "Reisnudeln mit Salat, Kräutern, Erdnüssen, hausgemachter Fischsauce und gebratenem Tofu", 13.9, "F", ["vegetarisch"]),
  D("26", "26", "Hauptspeisen", "Bun Vit", "Reisnudeln mit Salat, Kräutern, Erdnüssen, hausgemachter Fischsauce und knuspriger Ente", 14.9, "5, 7, D, E", ["beliebt"]),
  D("27", "27", "Hauptspeisen", "Bun Nem", "Reisnudeln mit Salat, Kräutern, Erdnüssen, hausgemachter Fischsauce und vietnamesischen Frühlingsrollen", 14.5, "5, 7, D, E"),
  D("28", "28", "Hauptspeisen", "Bun Bo Nam Bo", "Reisnudeln mit Rindfleisch, Zwiebeln, Sojasprossen und Zitronengras", 14.9, "5, 7, E", ["beliebt"]),
  D("30", "30", "Nudelsuppen", "Pho Tofu", "Aromatische Brühe mit Reisbandnudeln, Frühlingszwiebeln, Sojasprossen, Koriander und Kräutern", 13.9, "F", ["vegetarisch"]),
  D("31", "31", "Nudelsuppen", "Pho Rindfleisch", "Aromatische Brühe mit Rindfleisch, Reisbandnudeln, Frühlingszwiebeln, Sojasprossen, Koriander und Kräutern", 14.9, "5, 7", ["beliebt"]),
  D("32", "32", "Nudelsuppen", "Pho Spezial", "Mit Garnelen, Rind und Hühnerfleisch", 16.9, "5, 7, B", ["beliebt"]),
  D("33", "33", "Nudelsuppen", "Tom Yum Udon-Nudelsuppe", "Mit Riesengarnelen, Lachs, Pak Choi, Karotten und Paprika", 16.9, "5, 7, B"),
  D("35", "35", "Nudelgerichte", "Pad Thai Tom", "Gebratene Reisbandnudeln mit Garnelen, Pak Choi, Paprika und Möhren nach Pad-Thai-Art", 15.9, "5, 7, B, E", ["scharf"], imagePool[7]),
  D("36", "36", "Nudelgerichte", "Udon", "Gebratene Udon-Nudeln mit Tempura Chicken, Pak Choi, Paprika und Teriyaki-Soße", 13.9, "5, 7, E", ["beliebt"]),
  D("37", "37", "Reisgerichte", "Gebratener Jasminreis mit knuspriger Ente", "Mit Möhren, Lauchzwiebeln, Sojasprossen, Edamame und Ei", 15.5, "5, 7, C, F", ["beliebt"]),
  D("38", "38", "Reisgerichte", "Gebratener Jasminreis mit Garnelen und Trüffel", "Mit Möhren, Lauchzwiebeln, Sojasprossen, Edamame und Ei", 16.5, "5, 7, B, C, F"),
  D("40", "40", "Nudelgerichte", "Gebratene Nudeln mit paniertem Hähnchen", "Mit Möhren, Lauchzwiebeln, Sojasprossen und Ei", 13.9, "5, 7, C, F"),
  D("41", "41", "Nudelgerichte", "Gebratene Nudeln mit Teriyaki Chicken", "Mit Möhren, Lauchzwiebeln, Sojasprossen und Ei", 14.5, "5, 7, C, F", ["beliebt"]),
  D("42", "42", "Nudelgerichte", "Gebratene Nudeln mit knuspriger Ente", "Mit Möhren, Lauchzwiebeln, Sojasprossen und Ei", 15.5, "5, 7, C, F", ["beliebt"]),
  D("43", "43", "Nudelgerichte", "Gebratene Nudeln mit Riesengarnelen und Trüffel", "Mit Möhren, Lauchzwiebeln, Sojasprossen und Ei", 15.5, "5, 7, B, C, F"),
  D("60", "60", "Gourmet", "Hühnerfleisch mit Sauce nach Wahl", "Mit Jasminreis, Saisongemüse und Sauce nach Wahl", 13.9, "5, 7"),
  D("61", "61", "Gourmet", "Paniertes Hühnerfleisch mit Sauce nach Wahl", "Mit Jasminreis, Saisongemüse und Sauce nach Wahl", 14.5, "5, 7, A1"),
  D("62", "62", "Gourmet", "Teriyaki Chicken mit Sauce nach Wahl", "Mit Jasminreis, Saisongemüse und Sauce nach Wahl", 14.9, "5, 7", ["beliebt"]),
  D("63", "63", "Gourmet", "Knusprige Ente mit Sauce nach Wahl", "Mit Jasminreis, Saisongemüse und Sauce nach Wahl", 15.5, "5, 7, A1", ["beliebt"]),
  D("64", "64", "Gourmet", "Rindfleisch mit Sauce nach Wahl", "Mit Jasminreis, Saisongemüse und Sauce nach Wahl", 14.9, "5, 7"),
  D("65", "65", "Gourmet", "Garnelen mit Sauce nach Wahl", "Mit Jasminreis, Saisongemüse und Sauce nach Wahl", 15.9, "7, B"),
  D("66", "66", "Gourmet", "Lachs mit Sauce nach Wahl", "Mit Jasminreis, Saisongemüse und Sauce nach Wahl", 16.9, "D"),
  D("67", "67", "Gourmet", "Tofu mit Sauce nach Wahl", "Mit Jasminreis, Saisongemüse und Sauce nach Wahl", 13.5, "F", ["vegetarisch"]),
  D("68", "68", "Vietnamesischer Wok", "Bo Xao Xa Ot", "Rindfleisch mit Frühlingszwiebeln, Paprika, Zitronengras, Chili und Duftreis", 15.5, "5, 7, E", ["scharf"]),
  D("69", "69", "Vietnamesischer Wok", "Ga Xao Gion", "Knusprige Hähnchenstücke mit Zwiebeln, Paprika und Duftreis", 15.5, "5, 7, E"),
  D("70", "70", "Chef's Sauce", "Roastbeef mit BBQ Sauce", "220 g, mit Kartoffelpüree, Süßkartoffel, Paprika, Brokkoli und Zucchini", 22.9, "5, 7, B, F", ["beliebt"]),
  D("71", "71", "Chef's Sauce", "Lachs mit Trüffel und BBQ Sauce", "Mit Kartoffelpüree, Süßkartoffel, Paprika, Brokkoli und Zucchini", 22.9, "5, 7, B, F"),
  D("75", "75", "Chef's Sauce", "Knusprige Ente mit Knoblauchbutter-Sauce", "Mit Kartoffelpüree, Süßkartoffel, Paprika, Brokkoli und Zucchini", 20.9, "5, 7, B, G, F", ["beliebt"]),
  D("76", "76", "Chef's Sauce", "Garnelen mit Trüffel und Knoblauchbutter-Sauce", "Mit Kartoffelpüree, Süßkartoffel, Paprika, Brokkoli und Zucchini", 22.9, "5, 7, B, G, F"),
  D("77", "77", "Chef's Sauce", "Roastbeef mit Knoblauchbutter-Sauce", "220 g, mit Kartoffelpüree, Süßkartoffel, Paprika, Brokkoli und Zucchini", 22.9, "5, 7, B, F"),
  D("80", "80", "Vegane Gerichte", "Pilzsauce", "Mit Seitan, Seetang, Gemüse und Reis", 13.9, "7, F, A1", ["vegetarisch", "vegan"]),
  D("81", "81", "Vegane Gerichte", "Austern-Sauce", "Mit Seitan, Seetang, Gemüse und Reis", 13.9, "7, B, F", ["vegetarisch", "vegan"]),
  D("155", "155", "Kinder Menü", "Dino Nudeln", "Gebratene Nudeln mit Gemüse und Ei", 8.9, "5, 7, C, F"),
  D("156", "156", "Kinder Menü", "Kleine Tiger Bites", "Knuspriges Hähnchenstück mit gedämpftem Reis", 9.9, "5, 7, A1, K"),

  ...[
    [100, "Avocado Nigiri", "2 Stück Avocado", 5.0, "", ["vegetarisch"]], [101, "Sake Nigiri", "2 Stück schottischer Lachs", 5.5, "D"],
    [102, "Maguro Nigiri", "2 Stück Thunfisch", 6.5, "D"], [103, "Ebi Nigiri", "2 Stück Garnelen", 5.5, "B"],
    [104, "Unagi Nigiri", "2 Stück Aal", 5.8], [105, "Kani Nigiri", "2 Stück Surimi", 5.5],
    [106, "Avocado Maki", "6 Stück Avocado", 5.8, "", ["vegetarisch"]], [107, "Kappa Maki", "6 Stück Gurke", 5.5, "", ["vegetarisch"]],
    [108, "Sake Maki", "6 Stück schottischer Lachs", 6.0, "D"], [109, "Tekka Maki", "6 Stück Thunfisch", 6.9, "D"],
    [110, "Ebi Maki", "6 Stück Ebi", 5.9, "B"], [111, "Unagi Maki", "6 Stück Aal", 6.5, "D"],
    [112, "Kani Maki", "6 Stück Surimi", 5.9, "C, D"]
  ].map(([code, name, description, price, allergens = "", tags = []]) => D(String(code), String(code), "Sushi - Nigiri & Maki", name, description, price, allergens, tags)),
  D("120", "120", "Sushi - Inside-Out", "Veggie Freshness", "Avocado, Gurke, Mango, Frischkäse, Rucola und Sesam, 8 Stück", 9.9, "C, K", ["vegetarisch"]),
  D("121", "121", "Sushi - Inside-Out", "Sesam Kiss", "Chicken, Seetang, Frischkäse und Sesam, 8 Stück", 10.9, "C, D, K"),
  D("122", "122", "Sushi - Inside-Out", "Schwarzwald Gockel", "Tempura Chicken, Gurke, Frischkäse, Rucola und Sesam, 8 Stück", 10.9, "5, 7, C, K", ["beliebt"]),
  D("123", "123", "Sushi - Inside-Out", "Crab & Caviar Special", "Surimi, Avocado, Frischkäse und Kaviar, 8 Stück", 10.5, "B, C"),
  D("125", "125", "Sushi - Special Rolls", "All Green Everything", "Gurke, Mango, Rucola und Frischkäse, mit Avocado umwickelt, 8 Stück", 11.5, "C", ["vegetarisch"]),
  D("126", "126", "Sushi - Special Rolls", "Smoky Salmon Shrimp", "Tempura Ebi, Gurke, Frischkäse und Kaviar, mit flambiertem Lachs umwickelt, 8 Stück", 15.5, "B, C, D", ["beliebt"]),
  D("127", "127", "Sushi - Special Rolls", "Unagi Roll", "Tempura Ebi, Avocado und Frischkäse, mit Aal umwickelt, 8 Stück", 15.5),
  D("128", "128", "Sushi - Special Rolls", "Salmon Volcano", "Lachs, Avocado und Frischkäse, mit Lachs, Kaviar und Sesamblättern umwickelt, 8 Stück", 15.5, "C, D"),
  D("129", "129", "Sushi - Special Rolls", "Maguro Master Roll", "Thunfisch, Gurke, Rucola und Frischkäse, mit Thunfisch, Kaviar und Sesamblättern umwickelt, 8 Stück", 16.5, "C, D"),
  D("130", "130", "Sushi - Special Rolls", "Surf & Turf Roll", "Hähnchen, Gurke und Frischkäse, getoppt mit flambiertem Rinderhackfleisch und Rucola, 8 Stück", 15.5, "C, D"),
  D("135", "135", "Sushi - Tempura Rolls", "Crunchy Buddha", "Mini Roll mit Gurke, 8 Stück", 6.9, "A1", ["vegetarisch"]),
  D("136", "136", "Sushi - Tempura Rolls", "Salmon Crunch", "Mini Roll mit Lachs, 8 Stück", 8.5, "A1, D"),
  D("137", "137", "Sushi - Tempura Rolls", "Crispy Crab Stick", "Mini Roll mit Surimi, 8 Stück", 7.5, "A1, D"),
  D("138", "138", "Sushi - Tempura Rolls", "Mega Veggie", "Avocado, Gurke, Mango, Paprika, Rucola und Frischkäse, 6 Stück", 11.0, "A1, C", ["vegetarisch"]),
  D("139", "139", "Sushi - Tempura Rolls", "Mega Chicken Crunch", "Chicken, Gurke, Mango und Chili-Chicken, 6 Stück", 12.0, "5, 7, A1", ["scharf"]),
  D("140", "140", "Sushi - Tempura Rolls", "Mega Sake Crunch", "Lachs, Avocado, Gurke, Paprika, Frischkäse und Rucola, 6 Stück", 14.5, "A1, C, D"),
  D("145", "145", "Sushi Menüs", "Veggi", "6 Maki Gurke und 8 Inside-Out mit Avocado, Gurke, Mango, Frischkäse, Rucola und Sesam", 14.5, "C, K", ["vegetarisch"]),
  D("146", "146", "Sushi Menüs", "Minako", "6 Maki Sake, 2 Nigiri mit Lachs und Thunfisch sowie 8 Inside-Out mit Surimi, Avocado, Frischkäse und Kaviar", 19.9, "B, C, D"),
  D("147", "147", "Sushi Menüs", "Ohayo", "2 Nigiri mit Lachs und Ebi sowie 6 Tempura Futo mit Lachs, Avocado, Gurke, Paprika, Frischkäse und Rucola", 18.5, "A1, C, D", ["beliebt"]),
  D("148", "148", "Sashimi & Tataki", "Sake Sashimi", "6 Scheiben Lachs mit Kaviar", 13.5, "D"),
  D("149", "149", "Sashimi & Tataki", "Moniavase", "6 Scheiben: 3 Lachs, 3 Thunfisch und Kaviar", 14.9, "D"),
  D("150", "150", "Sashimi & Tataki", "Lachs Tataki", "8 Scheiben Lachs mit feinem Trüffel-Aroma", 18.6, "D"),
  D("151", "151", "Sashimi & Tataki", "Thunfisch Tataki", "8 Scheiben Thunfisch", 19.0, "D"),
  D("190", "190", "Menüs für mehrere Personen", "Menü für 2 Personen", "Pro Person: Suppe; Sommerrollen; Nigiri; Inside-Out Sushi; Ente Curry; gebackene Banane, Mochi und Crème brûlée", 27.5, "", ["beliebt"]),
  D("191", "191", "Menüs für mehrere Personen", "Menü für 4 Personen", "Pro Person: Vorspeisen; Nigiri, Tempura, Sashimi und Special Inside-Out Sushi; Roastbeef mit BBQ Sauce; Garnelen mit Knoblauchbutter-Sauce; Dessert", 39.9, "", ["beliebt"]),
  D("200", "200", "Desserts", "Japanische Mochi", "2 Stück, Matcha- und Maracuja-Geschmack", 5.0, "7", ["vegetarisch"]),
  D("201", "201", "Desserts", "Banane & Mochi", "Gebackene Bananen und Mochi", 6.0, "11, G", ["vegetarisch"]),
  D("202", "202", "Desserts", "Crème brûlée", "Französische Vanillecreme mit karamellisierter Zuckerkruste", 6.5, "G", ["vegetarisch"]),

  ...[
    ["K1", "Kaffee", "Heißgetränk", 3.5, "11"], ["K2", "Espresso", "Heißgetränk", 2.5, "11"],
    ["K3", "Cappuccino", "Heißgetränk", 3.8, "11, G"], ["K4", "Milchkaffee", "Heißgetränk", 3.9, "11, G"],
    ["K5", "Latte Macchiato", "Heiß oder kalt", 4.5, "11, G"], ["K6", "Heiße Schokolade", "Heißgetränk", 4.0, "11, G"],
    ["T1", "Jasmintee", "Traditioneller Homemade Tee", 4.5], ["T2", "Ingwer Minze Tee", "Traditioneller Homemade Tee", 5.0],
    ["T3", "Matcha Tee", "Traditioneller Homemade Tee", 5.0]
  ].map(([code, name, description, price, allergens = ""]) => D(code, code, "Kaffee & Tee", name, description, price, allergens)),
  ...[
    ["W1", "Still / Sprudel", "0,4 l", 3.5], ["W2", "Still / Sprudel Karaffe", "Mit Gurke und Minze", 6.5],
    ["H1", "Matcha Ice Tea Twist", "Matcha, Fuze Tea Pfirsich und Limette", 5.5], ["H2", "Passion", "Maracuja, Hibiskus, Minze und Soda", 5.5],
    ["H3", "Litchi Fresh", "Lychee, Limetten, Minze und Soda", 5.9], ["H4", "Ginger Special", "Maracuja, Ginger Ale, Minze und Soda", 5.9],
    ["H5", "Asian Cooler", "Limetten, Ginger Ale, Ingwer und Minze", 5.9], ["H6", "Blue Coco", "Kokoswasser, blauer Schmetterling und Minze", 5.9],
    ["H7", "Ruby Berry", "Wild Berry, Limetten, Minze und Beerenmix", 5.5, "1"], ["M1", "Matcha Latte", "Matcha und Milch", 5.6, "11, G"],
    ["M2", "Matcha Dream", "Matcha, Kokoswasser und Aloe Vera", 5.3, "11, G"], ["M3", "Matcha Latte Strawberry", "Matcha, Milch und Erdbeere", 5.3, "6, 11"],
    ["S1", "Coca Cola", "Flasche 0,3 l", 4.0, "11"], ["S2", "Cola Zero", "Flasche 0,3 l", 4.0, "1, 7, 8, 11"],
    ["S3", "Mezzo Mix", "Flasche 0,3 l", 4.0, "1, 11"], ["S4", "Fanta Orange", "Flasche 0,3 l", 4.0, "1, 6"],
    ["S5", "Sprite", "Flasche 0,3 l", 4.0, "1"], ["S6", "Schweppes Ginger Ale", "0,4 l", 4.3, "1"],
    ["S7", "Schweppes Wild Berry", "0,4 l", 4.3, "1"], ["S8", "Fuze Tea", "0,4 l", 4.0],
    ["J1", "Apfel", "Saft oder Schorle, 0,4 l", 4.3], ["J2", "Johannisbeere", "Saft oder Schorle, 0,4 l", 4.3, "6"],
    ["J3", "Maracuja", "Saft oder Schorle, 0,4 l", 4.3, "6"], ["J4", "Lychee", "Saft oder Schorle, 0,4 l", 4.3, "6"],
    ["MO1", "Asia Ginger Mule", "Alkoholfreier Cocktail mit Ginger Ale, Ingwer und Limette", 5.9],
    ["MO2", "Asian Lychee Fizz", "Alkoholfreier Cocktail mit Lychee, Limetten, Minze und Soda", 6.3]
  ].map(([code, name, description, price, allergens = ""]) => D(code, code, "Getränke", name, description, price, allergens)),
  ...[
    ["C1", "Maitai", "Orangensaft und Tropic-Aroma", 8.9, "1, 2, 11"], ["C2", "Pina Colada", "Ananassaft und Kokos-Aroma", 8.9, "6, G"],
    ["C3", "Zombie", "Ananassaft, Orangen- und Mandel-Aroma", 7.9], ["C4", "Sex on the Beach", "Vodka, Peach Schnapps, Orangensaft und Cranberrysaft", 8.9],
    ["A1", "Hugo", "Aperitif", 6.9, "L"], ["A2", "Aperol Spritz", "Aperitif", 6.9, "1, L"], ["A3", "Lillet Berry", "Aperitif", 6.9, "1, L"],
    ["BIR1", "Ganter Pils", "0,33 l", 3.5], ["BIR2", "Ganter ohne Alkohol", "0,33 l", 3.7],
    ["BIR3", "Ganter Hefeweizen", "0,5 l", 5.3, "6, G"], ["BIR4", "Ganter Hefeweizen ohne Alkohol", "0,5 l", 5.3, "6, G"],
    ["BIR5", "Asian Bier Kirin", "0,33 l", 4.5, "1"], ["SE1", "Sekt", "Glas, trocken, 12 % Vol.", 4.5],
    ["SE2", "Rotkäppchen Sekt", "Flasche 0,75 l, trocken, 12 % Vol.", 20.9], ["SA1-W", "Choyu Sake warm", "Japanischer Reiswein im Krug", 5.9, "L"],
    ["SA1-K", "Choyu Sake kalt", "Japanischer Reiswein im Krug", 7.5, "L"], ["WH1", "Hibiki", "Japanischer Whisky, 2 cl", 5.9, "1"]
  ].map(([id, name, description, price, allergens = ""]) => D(id, id.replace(/-.*/, ""), "Cocktails & Alkohol", name, description, price, allergens)),
  ...[
    ["WW1", "Chardonnay", "Glas 0,2 l, Domaine de Tholomies (Bio)", 5.9], ["WW2", "Weißweinschorle", "Glas 0,2 l", 5.9],
    ["WW3", "Chardonnay", "Flasche 0,75 l, Domaine de Tholomies (Bio)", 24.9], ["WW4", "Grauburgunder", "Flasche 0,75 l, Weingut Ellermann-Spiegel", 24.9],
    ["RW1", "Spätburgunder", "Glas 0,2 l, Qualitätswein Baden", 6.5], ["RW2", "Rotweinschorle", "Glas 0,2 l", 6.5],
    ["RW3", "Spätburgunder", "Flasche 0,75 l, Qualitätswein Baden", 25.9]
  ].map(([code, name, description, price]) => D(code, code, "Wein", name, description, price, "L")),
  ...[
    ["EX1", "Tofu", 2.0], ["EX2", "Reis", 2.0], ["EX3", "Reisnudeln", 2.5], ["EX4", "Fleisch", 3.5],
    ["EX5", "Ente", 9.5], ["EX6", "Garnele", 1.8, "1 Stück"], ["EX7", "Sauce nach Wahl", 2.0]
  ].map(([code, name, price, description = "Extra Portion"]) => D(code, code, "Extras", name, description, price))
];
